import bcrypt from "bcryptjs";
const data = {
  orders: [
    {
      orderItems: [
        {
          name: " vivobook",
          Image: "/images/product2.png",
          price: 200000,
          countInStock: 5,
          product: "62792654e22cd29c68af8408",
          qty: 1,
        },
      ],
      shippingAddress: {
        fullName: "keziz mouayed",
        address: "khenchela",
        city: "ouled rechache",
        postalCode: "40013",
      },
      itemsPrice: "100",
      shippingPrice: "20",
      totalPrice: "120",
      user: "627e68f3e59f0e9f65c3a4db",
      traite: false,
    },
    {
      orderItems: [
        {
          name: " vivobook",
          Image: "/images/product2.png",
          price: 200000,
          countInStock: 5,
          product: "62792654e22cd29c68af8408",
          qty: 3,
        },
      ],
      shippingAddress: {
        fullName: "moncef bouchenacha",
        address: "bouira",
        city: "ouladi aiche",
        postalCode: "9000",
      },
      itemsPrice: "100",
      shippingPrice: "20",
      totalPrice: "120",
      user: "627e68f3e59f0e9f65c3a4dc",
      traite: true,
    },
  ],
  users: [
    {
      name: "amine",
      lastname: "hamoutene",
      email: "amine@estin.dz",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
      wilaya: "15-Tizi-Ouzou",
      phone: "7777777777",
    },
    {
      name: "mouayed",
      lastname: "keziz",
      email: "mouayed@estin.dz",
      password: bcrypt.hashSync("6969", 8),
      isAdmin: false,
      wilaya: "40-Khenchela",
      phone: "6666666666",
    },

    {
      name: "moncef",
      lastname: "bouchenacha",
      email: "mo@estin.dz",
      password: bcrypt.hashSync("123456", 8),
      isAdmin: false,
      wilaya: "09-Blida",
      phone: "5555555555",
    },
  ],

  products: [
    {
      _name: "MX Master 3",
      brand: "LOGITECK",
      image: ["/images/mouse1_1.jpg"],
      category: "accessories",
      price: "5000",
      countInStock: 10,
      rating: 5,
    },
    {
      _name: "Paracon Mechanical Keyboard",
      brand: "PARACON",
      image: ["/images/keyboard1_1.jpg"],
      category: "accessories",
      price: "5000",
      countInStock: 10,
      rating: 5,
    },
    {
      _name: "Logitack Headset G-712",
      brand: "LOGITECK",
      image: ["/images/headset1_1.jpg", "/images/headset1_2.jpg"],
      category: "accessories",
      price: "7000",
      countInStock: 10,
      rating: 5,
    },
    {
      _name: "Canon EOS Rebel T6i DSLR Camera",
      brand: "CANON",
      image: [
        "/images/camera1_1.jpg",
        "/images/camera1_2.jpg",
        "/images/camera1_3.jpg",
        "/images/camera1_4.jpg",
      ],
      category: "camera",
      price: "110000",
      countInStock: 10,
      rating: 5,
    },
    {
      _name: "Canon EOS 80D",
      brand: "CANON",
      image: [
        "/images/camera2_1.jpg",
        "/images/camera2_2.jpg",
        "/images/camera2_3.jpg",
        "/images/camera2_4.jpg",
      ],
      category: "camera",
      price: "70000",
      countInStock: 10,
      rating: 5,
    },
    {
      _name: "Nikon D7500 Tamron 18-200mm",
      brand: "CANON",
      image: [
        "/images/camera3_1.jpg",
        "/images/camera3_2.jpg",
        "/images/camera3_3.jpg",
        "/images/camera3_4.jpg",
        "/images/camera3_5.jpg",
      ],
      category: "camera",
      price: "130000",
      countInStock: 10,
      rating: 5,
    },
    {
      _name: "Legion 5 Gen 6 (15” AMD) Gaming Laptop",
      brand: "LENOVO",
      processeur: "AMD Ryzen™ 7 5800H ",
      ram: "16GB",
      disque: "1TB SSD",
      gpu: "NVIDIA GeForce RTX 3070 ",

      image: [
        "/images/pc1_1.jpg",
        "/images/pc1_2.jpg",
        "/images/pc1_3.jpg",
        "/images/pc1_4.jpg",
      ],

      category: "laptop",
      price: "270000",
      countInStock: 10,
      rating: 5,
    },
    {
      _name: "ThinkPad T15 (Intel)",
      brand: "LENOVO",
      processeur: "Intel® Core™ i7, 10th gen",
      ram: "16GB",
      disque: "512GB SSD",
      gpu: "NVIDIA® GeForce® MX330 2GB GDDR5",

      image: [
        "/images/pc2_1.jpg",
        "/images/pc2_2.jpg",
        "/images/pc2_3.jpg",
        "/images/pc2_4.jpg",
        "/images/pc2_5.jpg",
      ],

      category: "laptop",
      price: "170000",
      countInStock: 10,
      rating: 5,
    },
    {
      _name: "ASUS VIVOBOOK R415EA-EK995W GRIS",
      brand: "ASUS",
      processeur: "AMD Ryzen™ 5 4800U ",
      ram: "16GB",
      disque: "512TO SSD",
      gpu: "NVIDIA GeForce RTX 1660TI ",

      image: [
        "/images/pc3_1.jpg",
        "/images/pc3_2.jpg",
        "/images/pc3_3.jpg",
        "/images/pc3_4.jpg",
      ],

      category: "laptop",
      price: "220000",
      countInStock: 10,
      rating: 5,
    },
  ],
};

export default data;
