import bcrypt from "bcryptjs";
const data = {
  orders: [
    {
      orderItems: [
        {
          name: " vivobook",
          Image: "/images/product2.png",
          price: 200000,
          countInStock: 5,
          product: "62792654e22cd29c68af8408",
          qty: 1,
        },
      ],
      shippingAddress: {
        fullName: "keziz mouayed",
        address: "khenchela",
        city: "ouled rechache",
        postalCode: "40013",
      },
      itemsPrice: "100",
      shippingPrice: "20",
      totalPrice: "120",
      user: "627e68f3e59f0e9f65c3a4db",
      traite: false,
    },
    {
      orderItems: [
        {
          name: " vivobook",
          Image: "/images/product2.png",
          price: 200000,
          countInStock: 5,
          product: "62792654e22cd29c68af8408",
          qty: 3,
        },
      ],
      shippingAddress: {
        fullName: "moncef bouchenacha",
        address: "bouira",
        city: "ouladi aiche",
        postalCode: "9000",
      },
      itemsPrice: "100",
      shippingPrice: "20",
      totalPrice: "120",
      user: "627e68f3e59f0e9f65c3a4dc",
      traite: true,
    },
  ],
  users: [
    {
      name: "amine",
      lastname: "hamoutene",
      email: "amine@estin.dz",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
      wilaya: "15-Tizi-Ouzou",
      phone: "7777777777",
    },
    {
      name: "mouayed",
      lastname: "keziz",
      email: "mouayed@estin.dz",
      password: bcrypt.hashSync("6969", 8),
      isAdmin: false,
      wilaya: "40-Khenchela",
      phone: "6666666666",
    },

    {
      name: "moncef",
      lastname: "bouchenacha",
      email: "mo@estin.dz",
      password: bcrypt.hashSync("123456", 8),
      isAdmin: false,
      wilaya: "09-Blida",
      phone: "5555555555",
    },
  ],

  products: [
    {
      _name: "asus vivobook",
      brand: "asus",
      processeur: "i 5 8eme generation",
      ram: "8GO",
      disque: "250Go SSD",
      gpu: "RTX 3060",
      Image: "/images/product2.png",
      category: "laptop",
      price: 200000,
      countInStock: 8,
      rating: 4,
    },
    {
      _name: "mac book",
      brand: "apple",
      processeur: "m1",
      ram: "8GO",
      disque: "250Go SSD",
      gpu: "radeom 8800",
      Image: "/images/macbook.png",
      category: "laptop",
      price: 210000,
      countInStock: 10,
      rating: 4,
    },
    {
      _name: "asus rog zephrus g14",
      brand: "asus",
      processeur: "ryzen 7 4th",
      ram: "16GO",
      disque: "512Go SSD",
      gpu: "RTX 2060",
      Image: "/images/zef.jpg",
      category: "laptop",
      price: 200000,
      countInStock: 10,
      rating: 4,
    },
    {
      _name: "galaxy S9",
      brand: "samsung",
      processeur: "test processeur i7",
      ram: "4GO",
      disque: "64GB",
      gpu: "RTX 3060",
      Image: "/images/S9.png",
      category: "laptop",
      price: 200000,
      countInStock: 10,
      rating: 4,
    },
    {
      _name: "DELL LATITUDE E5550",
      brand: "DELL",
      processeur: "i7 7eme generation",
      ram: "18GB",
      disque: "250Go SSD",
      gpu: "RTX 3060",
      Image: "/images/dell.jpg",
      category: "laptop",
      price: 200000,
      countInStock: 10,
      rating: 4,
    },
    {
      _name: "Iphone 13",
      brand: "apple",
      processeur: "i 5 8eme generation",
      ram: "8GO",
      disque: "test disque 69GB",
      gpu: "RTX 3060",
      Image: "/images/iphone.png",
      category: "phone",
      price: 300000,
      countInStock: 10,
      rating: 4,
    },
    {
      _name: "rog duo",
      brand: "asus",
      processeur: "i 5 8eme generation",
      ram: "8GO",
      disque: "250Go SSD",
      gpu: "test gpu RTX 9999 TI",
      Image: "/images/rogduo.png",
      category: "laptop",
      price: 200000,
      countInStock: 10,
      rating: 4,
    },
    {
      _name: "asus vivobook",
      brand: "asus",
      processeur: "i 5 8eme generation",
      ram: "8GO",
      disque: "250Go SSD",
      gpu: "RTX 3060",
      Image: "/images/product2.png",
      category: "test category",
      price: 200000,
      countInStock: 10,
      rating: 4,
    },
    {
      _name: "asus phone",
      brand: "asus",
      processeur: "i 5 8eme generation",
      ram: "8GO",
      disque: "250Go SSD",
      gpu: "RTX 3060",
      Image: "/images/product2.png",
      category: "phone",
      price: 200000,
      countInStock: 5,
      rating: 4,
    },
    {
      _name: " vivobook",
      brand: "acus",
      processeur: "i 3 8eme generation",
      ram: "816O",
      disque: "500Go SSD",
      gpu: "RTX 3060",
      Image: "/images/product-1.jpg",
      category: "laptop",
      price: 200000,
      countInStock: 5,
      rating: 4,
    },

    {
      _name: " vivobook",
      brand: "acus",
      processeur: "i 3 8eme generation",
      ram: "816O",
      disque: "500Go SSD",
      gpu: "RTX 3060",
      Image: "/images/product-3.jpg",
      category: "laptop",
      price: 200000,
      countInStock: 5,
      rating: 4,
    },

    {
      _name: " vivobook",
      brand: "acus",
      processeur: "i 3 8eme generation",
      ram: "816O",
      disque: "500Go SSD",
      gpu: "RTX 3060",
      Image: "/images/product2.png",
      category: "laptop",
      price: 200000,
      countInStock: 5,
      rating: 4,
    },
    {
      _name: " vivobook",
      brand: "acus",
      processeur: "i 3 8eme generation",
      ram: "816O",
      disque: "500Go SSD",
      gpu: "RTX 3060",
      Image: "/images/product2.png",
      category: "laptop",
      price: 200000,
      countInStock: 5,
      rating: 4,
    },
    {
      _name: " vivobook",
      brand: "acus",
      processeur: "i 3 8eme generation",
      ram: "816O",
      disque: "500Go SSD",
      gpu: "RTX 3060",
      Image: "/images/product2.png",
      category: "laptop",
      price: 200000,
      countInStock: 5,
      rating: 4,
    },
  ],
};

export default data;
