export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_EDIT_INFO_REQUEST = "USER_EDIT_INFO_REQUEST";
export const USER_EDIT_INFO_SUCCESS = "USER_EDIT_INFO_SUCCESS";
export const USER_EDIT_INFO_FAIL = "USER_EDIT_INFO_FAIL";

//signout {request, success, fail}
export const USER_SIGNOUT = "USER_SIGNOUT";
